"""Tests for martingale.diagnostics — exact log-ratios, lag buckets, ESS, lag-0 floor."""
import math
from fractions import Fraction

import pytest
from click.testing import CliRunner

from martingale.cli import cli
from martingale.diagnostics import attribute, decompose, diagnosis, render_markdown, scored_tokens
from martingale.record import Recorder, SamplerConfig, bits_to_fraction, float_bits

S = SamplerConfig(temperature=1.0)
TOK = "f" * 64


def _ws(tmp_path):
    rec = Recorder(tmp_path / "ws")
    r0 = rec.publish_revision("1" * 64, TOK, S, step=0)
    r1 = rec.publish_revision("2" * 64, TOK, S, step=1)
    r3 = rec.publish_revision("3" * 64, TOK, S, step=3)
    # seq A generated by r0, scored by r0 (lag 0) with a tiny engine mismatch
    with rec.sequence(0, "a", [1]) as a:
        a.token(r0.digest, 5, -0.5); a.token(r0.digest, 6, -1.0)
    rec.score(a.record.digest, r0.digest, [-0.5, -1.0 + 1e-6])
    # seq B generated by r0, scored by r3 (lag 3), ratios 2 and 1/2
    with rec.sequence(0, "b", [1]) as b:
        b.token(r0.digest, 5, -1.0); b.token(r0.digest, 6, -1.0)
    rec.score(b.record.digest, r3.digest, [-1.0 + math.log(2), -1.0 - math.log(2)])
    # seq C mixed r0/r1, scored by r3 (lags 3 and 2), unscored seq D
    with rec.sequence(1, "c", [1]) as c:
        c.token(r0.digest, 5, -0.7); c.token(r1.digest, 6, -0.7)
    rec.score(c.record.digest, r3.digest, [-0.7, -0.7])
    with rec.sequence(1, "d", [1]) as d:
        d.token(r1.digest, 5, -0.7)
    return rec


class TestScoredTokens:
    def test_log_ratio_is_exact_difference_of_bits(self, tmp_path):
        rec = _ws(tmp_path)
        toks = list(scored_tokens(rec.ledger))
        lag0 = [t for t in toks if t.lag == 0]
        assert len(lag0) == 2
        assert lag0[0].log_ratio == 0
        expected = bits_to_fraction(float_bits(-1.0 + 1e-6)) - bits_to_fraction(float_bits(-1.0))
        assert lag0[1].log_ratio == expected and isinstance(lag0[1].log_ratio, Fraction)

    def test_lags_and_mixed_flag(self, tmp_path):
        rec = _ws(tmp_path)
        lags = sorted(t.lag for t in scored_tokens(rec.ledger))
        assert lags == [0, 0, 2, 3, 3, 3]
        assert {t.mixed_sequence for t in scored_tokens(rec.ledger) if t.lag == 2} == {True}


class TestDecompose:
    def test_histogram_floor_and_counts(self, tmp_path):
        d = decompose(_ws(tmp_path).ledger)
        assert d["staleness_histogram"] == {"0": 2, "2": 1, "3": 3}
        assert d["n_sequences"] == 4 and d["n_unscored_sequences"] == 1 and d["n_mixed_sequences"] == 1
        assert d["lag0_floor"]["n_tokens"] == 2
        assert d["lag0_floor"]["float_informational"]["max_abs_log_ratio"] < 2e-6

    def test_ess_and_clipped_fraction_for_known_ratios(self, tmp_path):
        d = decompose(_ws(tmp_path).ledger, eps=(0.2,))
        b3 = next(b for b in d["by_lag"] if b["lag"] == 3)
        f = b3["float_informational"]
        # ratios at lag 3: 2, 1/2 (seq B) and 1 (seq C token 0)
        s1, s2 = 2 + 0.5 + 1, 4 + 0.25 + 1
        assert f["ess"] == pytest.approx(s1 * s1 / s2, rel=1e-6)
        assert f["clipped_fraction"]["0.2"] == pytest.approx(2 / 3)
        assert f["ratio_max"] == pytest.approx(2.0, rel=1e-6)
        assert b3["n_sequences"] == 2 and b3["n_mixed_sequences"] == 1

    def test_exact_fields_are_reduced_fraction_strings(self, tmp_path):
        d = decompose(_ws(tmp_path).ledger)
        for b in d["by_lag"]:
            for k in ("mean_log_ratio", "mean_abs_log_ratio", "max_abs_log_ratio"):
                num, den = b[k].split("/")
                assert math.gcd(int(num), int(den)) == 1

    def test_markdown_renders(self, tmp_path):
        md = render_markdown(decompose(_ws(tmp_path).ledger))
        assert "Engine-mismatch floor (lag 0)" in md and "| 3 |" in md

    def test_cli_report(self, tmp_path):
        _ws(tmp_path)
        r = CliRunner().invoke(cli, ["report", "--dir", str(tmp_path / "ws"), "--json", str(tmp_path / "r.json")])
        assert r.exit_code == 0, r.output
        assert "lag" in r.output and (tmp_path / "r.json").exists()

    def test_cli_report_without_record_fails(self, tmp_path):
        r = CliRunner().invoke(cli, ["report", "--dir", str(tmp_path)])
        assert r.exit_code == 1


class TestAttribution:
    def test_shares_are_exact_and_sum_to_one(self, tmp_path):
        d = decompose(_ws(tmp_path).ledger)
        a = attribute(d)
        stale = Fraction(a["staleness_share"]); engine = Fraction(a["engine_share"])
        assert stale + engine == 1 and 0 <= stale <= 1
        # floor is tiny here (1e-6), so almost everything is staleness
        assert stale > Fraction(99, 100)

    def test_no_lag0_means_unknown_floor(self, tmp_path):
        rec = Recorder(tmp_path / "ws")
        r0 = rec.publish_revision("1" * 64, TOK, S, step=0)
        r2 = rec.publish_revision("2" * 64, TOK, S, step=2)
        with rec.sequence(0, "a", [1]) as a:
            a.token(r0.digest, 5, -0.5)
        rec.score(a.record.digest, r2.digest, [-0.9])
        d = decompose(rec.ledger)
        assert attribute(d)["staleness_share"] is None
        assert any("No lag-0 tokens" in line for line in diagnosis(d))

    def test_diagnosis_mentions_large_floor_and_negative_lag(self, tmp_path):
        rec = Recorder(tmp_path / "ws")
        r0 = rec.publish_revision("1" * 64, TOK, S, step=0)
        r1 = rec.publish_revision("2" * 64, TOK, S, step=1)
        r5 = rec.publish_revision("3" * 64, TOK, S, step=5)
        with rec.sequence(0, "a", [1]) as a:
            a.token(r5.digest, 5, -0.5)
        rec.score(a.record.digest, r5.digest, [-0.6])          # lag 0, floor 0.1 (large)
        with rec.sequence(0, "b", [1]) as b:
            b.token(r5.digest, 5, -0.5)
        rec.score(b.record.digest, r1.digest, [-0.5])          # negative lag
        with rec.sequence(0, "c", [1]) as c:
            c.token(r0.digest, 5, -0.5)
        rec.score(c.record.digest, r5.digest, [-0.7])          # lag 5
        lines = diagnosis(decompose(rec.ledger))
        assert any("engine floor is large" in line for line in lines)
        assert any("OLDER step" in line for line in lines)

    def test_cli_doctor_and_report_alias(self, tmp_path):
        _ws(tmp_path)
        for cmd in ("doctor", "report"):
            r = CliRunner().invoke(cli, [cmd, "--dir", str(tmp_path / "ws")])
            assert r.exit_code == 0, r.output
            assert "is staleness and" in r.output
